release:
  runs-on: ${{ matrix.os }}
  strategy:
    matrix:
      os: [ ubuntu-18.04, windows-2019, macos-latest ]
  steps:
    - uses: actions/checkout@v3
    - uses: manoadamro/rust-release@v1
      with:
        owner: ${{ github.repository_owner }}
        repo: ${{ github.repository }}
        token: ${{ secrets.GITHUB_TOKEN }}